### ISSUE TITLE
Error: Extended public key export cancelled by user

### ISSUE THREAD

**Issue by parlange** [angelstakepool/add-hw-wallet-owner-to-pool#2]
Hi,

I am following Coincashew guide at step 18.14, secure your pool pledge with a 2nd pool owner using a hardware wallet.

My local machine is running Ubuntu 20.04 LTS and has the cardano-node and cardano-cli, as well as cardano-hw-cli.

The Trezor T is working on Ubuntu after adding its deb package. However, it is unable to export public key and create hw-stake.vkey

This is the error sign:

**Error: Extended public key export cancelled by user**

Hope there is a solution because this method definitely adds security to the pledge of the pool.

**Comment by angelstakepool** [comment]
> Hi,
> 
> 
> 
> I am following Coincashew guide at step 18.14, secure your pool pledge with a 2nd pool owner using a hardware wallet.
> 
> 
> 
> My local machine is running Ubuntu 20.04 LTS and has the cardano-node and cardano-cli, as well as cardano-hw-cli.
> 
> 
> 
> The Trezor T is working on Ubuntu after adding its deb package. However, it is unable to export public key and create hw-stake.vkey
> 
> 
> 
> This is the error sign:
> 
> 
> 
> **Error: Extended public key export cancelled by user**
> 
> 
> 
> Hope there is a solution because this method definitely adds security to the pledge of the pool.
> 
> 

Not sure, I have never used Trezor devices with cardano-hw-cli

edit: According to my enquiries, this could be the result of incompatible versions between cardano app in trezor and cardano-hw-cli; also use mary era instead of alonzo. Another cause could be the canonical order in the tx build if this address contains tokens

**Comment by parlange** [comment]
Thank you very much for your reply. I tried exporting keys using cardano-hw-cli with no success.
I can't find the Cardano app in Trezor, it just holds the keys and it syncs fine with any wallet, just not by CLI.

I found this article by adalite.io which shows how to become co-owner of a staking pool and pledge using a hardware wallet.
https://adalite.medium.com/cardano-stake-pool-owners-hw-support-6d9278dba0ba
The Trezor T syncs fine with adalite, so I might try this method.

**Comment by parlange** [comment]
I was able to export the public keys using:

`cardano-hw-cli address key-gen \
  --path 1852H/1815H/0H/2/0 \
  --verification-key-file hw-stake.vkey \
  --hw-signing-file hw-stake.hwsfile`

However, while witnessing with:

`cardano-hw-cli transaction witness \
  --tx-body-file tx-pool.raw \
  --hw-signing-file hw-stake.hwsfile \
  --mainnet \
  --out-file hw-stake.witness`

I get the following:

`Error: Invalid raw transaction CBOR
`
How can I witness using the same hw-stake.hwsfile I exported from the Trezor T?
